version: '2'

services:
  runner:
    restart: always
    image: elkemper/kubectl-gitlab-ci-runner:latest
    volumes:
    - /srv/docker/gitlab-runner:/home/gitlab_ci_multi_runner/data
    - $HOME/.kube:/home/gitlab_ci_multi_runner/.kube:ro
    environment:
    - CI_SERVER_URL= 
    - RUNNER_TOKEN= 
    - RUNNER_DESCRIPTION= 
    - RUNNER_EXECUTOR=shell
    